import dotenv from "dotenv";
dotenv.config();

export const ENV = {
  DATABASE_URL: process.env.DATABASE_URL,
  ALLOW_ORIGIN: process.env.ALLOW_ORIGIN,
  SUPERTOKENS_CONNECTION_URI: process.env.SUPERTOKENS_CONNECTION_URI,
  SUPERTOKENS_API_KEY: process.env.SUPERTOKENS_API_KEY,
  INCEPTION_WHATSAPP_SESSION_ID: process.env.INCEPTION_WHATSAPP_SESSION_ID,
};
