name: Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build production Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/inception-express:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            SUPERTOKENS_CONNECTION_URI=${{ secrets.SUPERTOKENS_CONNECTION_URI }}
            SUPERTOKENS_API_KEY=${{ secrets.SUPERTOKENS_API_KEY}}
            INCEPTION_WHATSAPP_SESSION_ID=${{ secrets.INCEPTION_WHATSAPP_SESSION_ID }}
